language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-20  ANDROID_ABI=armeabi-v7a
    
notifications:
  email: false
  
branches:
  only:
    - dev
    - master

android:
  components:
    - platform-tools
    - tools
    
    # The SDK version used to compile your project
    - android-20
    # The BuildTools version used by your project
    - build-tools-20.0.0
    
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-support
    - extra-android-m2repository
    - addon-google_apis-google-20

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-20
    - sys-img-x86-android-20    

before_install:
  
  # Gradle has been updated to version 2.0. 
  # This release contains potential breaking changes. 
  # If you need to go back to version 1.11, add the following to your .travis.yml:
  #
  - sudo rm -r /usr/local/gradle
  - curl -LO http://services.gradle.org/distributions/gradle-1.11-bin.zip
  - unzip -q gradle-1.11-bin.zip
  - sudo mv gradle-1.11 /usr/local/gradle
  - chmod +x gradlew

before_script:
  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a
  
  # Create and start emulator
  #- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  #- emulator -avd test -no-skin -no-audio -no-window &
  #- adb wait-for-device
  #- adb shell input keyevent 82 &
  


script: gradle assembleCI
